### ISSUE TITLE
reference: koki short

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetesx#46]
This is not an issue per-say but an idea for reference.

As you build this simplified Kubernetes API package you may wish to refer to
https://docs.koki.io/short/

They've put some effort into simplifying Kubernetes YAML without information loss. There is likely some useful inspiration there.

**Comment by pgavlin** [comment]
Thanks for the heads up--we'll take a look!

cc @lukehoban @lblackstone

**Comment by lukehoban** [comment]
Good reference for future investments - but no specific action needed here so will close out.
